#160451455 User should be able to reset password
andela/phlox-ah-frontend pull request #10
Opened 2018-11-07 09:42 UTC by kampkelly

What does this PR do?
This PR add functionality to reset a users password.

Description of Task to be completed?
add forgot password page
add reset password page
#### How should this be manually tested?
Go to the forgot password and reset password page.
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
#160451455

2018-11-07 09:42 UTC, kampkelly commented
Not ready for review until login feature is merged

2018-11-07 10:11 UTC, kampkelly commented on src/containers/Password/ForgotPassword.js
> +      if (this.props.errorMessage) {
this is the error message that shows if the forgot password email was sent successfully or not

2018-11-07 10:12 UTC, kampkelly commented on src/containers/Password/ResetPassword.js
> +    if (password.length < 6) {
this checks that the new password must be at least 6 letters

2018-11-08 10:22 UTC, s-akinrele commented on src/containers/Login/Login.scss
> +#login-modal, #reset-password-modal, #forgot-password-modal{
give the elements a className

2018-11-08 10:31 UTC, s-akinrele commented on src/containers/Password/ResetPassword.js
> +          <a href="#" onClick={this.onLoginClicked.bind(this)}>
Always bind in the constructor

2018-11-08 10:32 UTC, s-akinrele requested changes
I had some comments

2018-11-09 10:29 UTC, s-akinrele approved these changes

2018-11-09 10:33 UTC, merged