Setup store and container for user signup
andela/phlox-ah-frontend pull request #11
Opened 2018-11-08 00:05 UTC by udochukwu

**What does this PR do?**

- Users should be able to Signup and or Register using Sign up forms on the signup route.

**Description of Task to be completed?**

- Add signup feature

**What are the relevant pivotal tracker stories?**

- https://www.pivotaltracker.com/story/show/160451454

**Screenshots (if appropriate)**

- N/A

**Questions**

- N/A

2018-11-08 01:05 UTC, udochukwu commented on src/containers/Signup/Signup.js
> +        success
Show success message on successful signup

2018-11-08 01:06 UTC, udochukwu commented on src/containers/Signup/Signup.js
> +      {
hide signup form on successful signup

2018-11-08 01:08 UTC, udochukwu commented on src/containers/Signup/Signup.js
> +      {
hide signup form on successful signup

2018-11-08 01:08 UTC, udochukwu commented on src/containers/Signup/Signup.js
> +      {
Show success message on successful signup

2018-11-08 01:09 UTC, udochukwu commented on src/containers/Signup/Signup.js
> +      {
hide signup form on successful signup

2018-11-08 01:33 UTC, udochukwu commented on src/containers/Signup/Signup.js
> +      }
Show success message on successful signup

2018-11-08 01:34 UTC, udochukwu commented on src/containers/Signup/Signup.js
> +      && <div>
hide signup form on successful signup

2018-11-08 10:33 UTC, s-akinrele commented on src/containers/Header/Header.js
> +                  onClick={this.onSignupClicked.bind(this)}
move this to a constructor

2018-11-08 10:44 UTC, s-akinrele requested changes
As discussed

2018-11-09 10:27 UTC, s-akinrele approved these changes

2018-11-09 10:28 UTC, merged