#160451459 create article functionality
andela/phlox-ah-frontend pull request #12
Opened 2018-11-09 08:41 UTC by onwuvic

#### What does this PR do?
This pull request creates functionality to create an article in the frontend

#### Description of Task to be completed?
- Create JSX view form to create the article
- Create an action to create an article
- Create a reducer to create an article
- Write a test for the create article component

#### How should this be manually tested?
- Start the app
- Navigate to /api/v1/new-story
- create your article

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#160451459

2018-11-09 08:47 UTC, onwuvic commented on package.json
>      "react-materialize": "^2.4.8",
medium-editor for text-area tag.
react-idle-timer for checking the idle time of the user before calling the auto-save function
react-tag-input for adding tags

2018-11-09 08:48 UTC, onwuvic commented on src/components/Pages/LoginPage.js
> +      <input type='submit' name='Login' />
The position changed

2018-11-09 08:48 UTC, onwuvic commented on src/constants/Constants.js
> -  ALL_ARTICLES: `${BASE_URL}/api/v1/articles/feed`
The position changed

2018-11-09 08:49 UTC, onwuvic commented on src/containers/createArticle/CreateArticle.js
> +    this.update = this.update.bind(this);
I used bind because it won't work without binding

2018-11-09 08:59 UTC, onwuvic commented on src/reducers/Index.js
> -  Info: msgInfoReducer
The position changed

2018-11-09 09:02 UTC, onwuvic commented on src/styles/style.scss
> -    color: $themeColor;
This style was not needed anymore

2018-11-09 09:04 UTC, onwuvic commented on src/components/Pages/HomePage.js
> -    <h1 className="theme-color">Hello! Welcome to Authors Haven</h1>
This is not needed anymore

2018-11-09 09:04 UTC, onwuvic commented on src/App.js
> -        <MsgInfo />
This is not needed anymore

2018-11-09 09:27 UTC, onwuvic commented on src/App.js
> -import Home from './containers/Home/Home';
These import are no longer needed in this file

2018-11-09 10:09 UTC, s-akinrele commented on src/App.js
> +// import Home from './containers/Home/Home';
remove commented code

2018-11-09 10:10 UTC, s-akinrele commented on src/containers/Header/Header.js
> +                        onClick={this.logout.bind(this)}
bind in the constructor

2018-11-09 10:13 UTC, s-akinrele commented on src/containers/createArticle/CreateArticle.js
> +    const tags = TagObjectToString(this.state.tags);
just destructure as you are doing above

2018-11-09 10:14 UTC, s-akinrele commented on src/containers/createArticle/CreateArticle.js
> +      tags: tags.filter((tag, index) => index !== i),
rename  `i`

2018-11-09 10:15 UTC, s-akinrele commented on src/containers/createArticle/CreateArticle.js
> +    newTags.splice(newPos, 0, tag);
use the full spelling for readability purpose

2018-11-12 09:50 UTC, onwuvic commented on src/containers/createArticle/CreateArticle.js
> +    const tags = TagObjectToString(this.state.tags);
fixed

2018-11-12 10:19 UTC, s-akinrele commented on src/components/ArticleForm/ArticleForm.scss
> +}
add new line

2018-11-12 10:21 UTC, s-akinrele commented on src/containers/Header/Header.js
> +    this.logout = this.logout.bind(this);
change this as discussed

2018-11-12 10:24 UTC, s-akinrele commented on src/containers/createArticle/CreateArticle.js
> +    this.update = this.update.bind(this);
arrange in alphabetical order

2018-11-12 10:25 UTC, s-akinrele commented on src/containers/createArticle/CreateArticle.js
> +    this.setState({
tagIndexToDelete

2018-11-12 10:28 UTC, s-akinrele commented on src/containers/createArticle/CreateArticle.js
> +  render() {
const defaultValue = this.state.category ? this.state.category : 0

2018-11-12 10:30 UTC, s-akinrele commented on src/containers/createArticle/CreateArticle.js
> +                <Input s={12} type='select' id="category" onChange={this.onInputChange} defaultValue={this.state.category ? this.state.category : '0'} required>
```
<Input
 s={12}
 type='select'
 id="category"
 onChange={this.onInputChange}
 defaultValue={defaultValue}
 required
>
```

2018-11-12 10:31 UTC, s-akinrele commented on src/containers/createArticle/CreateArticle.scss
> +
remove unnecessary space

2018-11-12 10:32 UTC, s-akinrele commented on src/containers/createArticle/CreateArticle.scss
> +
remove this space

2018-11-12 10:33 UTC, s-akinrele commented on src/containers/createArticle/CreateArticle.test.js
> +    categories,
remove comma

2018-11-12 10:38 UTC, s-akinrele requested changes
I had some comments

2018-11-13 09:35 UTC, onwuvic commented on src/containers/createArticle/CreateArticle.js
> +    this.update = this.update.bind(this);
fixed

2018-11-13 09:36 UTC, onwuvic commented on src/containers/createArticle/CreateArticle.js
> +    this.setState({
fixed

2018-11-13 09:36 UTC, onwuvic commented on src/containers/createArticle/CreateArticle.js
> +  render() {
done

2018-11-13 09:37 UTC, onwuvic commented on src/containers/createArticle/CreateArticle.scss
> +
fixed

2018-11-13 09:49 UTC, onwuvic commented on src/containers/createArticle/CreateArticle.test.js
> +    categories,
fixed

2018-11-13 09:49 UTC, onwuvic commented on src/containers/createArticle/CreateArticle.scss
> +
fixed

2018-11-13 09:49 UTC, onwuvic commented on src/containers/createArticle/CreateArticle.js
> +                <Input s={12} type='select' id="category" onChange={this.onInputChange} defaultValue={this.state.category ? this.state.category : '0'} required>
fixed

2018-11-13 10:06 UTC, s-akinrele commented on src/containers/createArticle/CreateArticle.js
> +      formData.append('title', title);
extract this into a method

2018-11-13 10:07 UTC, s-akinrele commented on src/containers/createArticle/CreateArticle.js
> +              onImageChange={this.onImageChange}
remove all these `on`

2018-11-13 13:19 UTC, onwuvic commented on src/App.js
> +// import Home from './containers/Home/Home';
fixed

2018-11-14 10:06 UTC, s-akinrele approved these changes

2018-11-14 10:06 UTC, merged