#160451464 user should be able to view tags
andela/phlox-ah-frontend pull request #26
Opened 2018-11-21 09:42 UTC by kampkelly

What does this PR do?
This PR adds the page to view tags and the articles under a tag

Description of Task to be completed?
Show tags on the sidebar
#### How should this be manually tested?
Go to the root url, you should see a sidebar showing tags.
On clicking a tag, you should see articles under that tag
#### Any background context you want to provide?
None
### Screenshots

#
<img width="1267" alt="screen shot 2018-11-21 at 10 41 03 am" src="https://user-images.githubusercontent.com/23643904/48832693-0924cd80-ed7a-11e8-82ea-ad7c2cbff56d.png">
### What are the relevant pivotal tracker stories?
#160451464

2018-11-21 09:55 UTC, kampkelly commented on src/components/ArticleCard/ArticleCard.js
> +  if (props.pic === 'null') {
I did this check because I noticed that the null returned is a string and checking with `!props.pic `does not work as intended

2018-11-21 09:56 UTC, kampkelly commented on src/containers/Sidebar/Sidebar.js
> +  moreTags() {
this function is called to load more tags into the sidebar

2018-11-21 10:23 UTC, kampkelly commented on src/containers/Tag/ViewTag.test.js
> +});
I will add more test cases

2018-11-21 10:23 UTC, kampkelly commented on src/containers/Sidebar/Sidebar.test.js
> +});
I will add more test cases

2018-11-21 10:36 UTC, s-akinrele commented on src/containers/Tag/ViewTag.scss
> +}
add newline

2018-11-21 10:37 UTC, s-akinrele commented on src/containers/createArticle/CreateArticle.js
>      } else if (!this.state.loading && !this.state.success && this.state.error === true) {
`this.state.error `

2018-11-21 10:38 UTC, s-akinrele requested changes
Add more test

2018-11-22 10:11 UTC, s-akinrele approved these changes

2018-11-22 10:52 UTC, merged