#160451470 user can opt in and out notification
andela/phlox-ah-frontend pull request #30
Opened 2018-11-23 09:33 UTC by onwuvic

# Not Ready For Review

#### What does this PR do?
This pull request adds functionality for user to opt-in and opt-out of notification

#### Description of Task to be completed?
- Create settings Component
- Create settings Reducers
- Create settings Actions

#### How should this be manually tested?
None

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
#160451470

#### Questions:```
None

2018-11-26 09:38 UTC, onwuvic commented on src/constants/Constants.js
> -  MY_ARTICLES_URL: `${BASE_URL}/api/v1/myarticles`,
Move the `api/v1/` to the base URL.

2018-11-26 09:45 UTC, oladimillion commented
LGTM

2018-11-26 10:01 UTC, s-akinrele commented on src/containers/Header/Header.js
> +                          &nbsp; Settings
can you use css.. give it a margin

2018-11-26 10:03 UTC, s-akinrele commented on src/containers/Settings/Settings.js
> +  handleChange(checked, event, id) {
toggleButton

2018-11-26 10:04 UTC, s-akinrele commented on src/containers/Settings/Settings.js
> +    this.state = { notificationStatus: false };
define check in state.....

2018-11-26 10:07 UTC, s-akinrele commented on src/containers/Settings/Settings.js
> +  handleChange(checked, event, id) {
refactor as discussed

2018-11-26 10:08 UTC, s-akinrele requested changes
I had some comments

2018-11-28 07:43 UTC, onwuvic commented on src/index.js
> -  setAuthToken(localStorage.token);
This code was removed because it is a duplication of an existing code

2018-11-28 10:29 UTC, s-akinrele approved these changes

2018-11-28 10:29 UTC, merged